name: Get aria2c lines

on:
  push:
    branches: [main]

jobs:
  get_aria2c_lines:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: List files
        id: list_files
        run: |
          curl -s https://api.github.com/repos/camenduru/stable-diffusion-webui-colab/contents/nightly?ref=main \
          | jq -r '.[].download_url' > file_urls.txt
      - name: Download files
        run: |
          while read -r url; do
            curl -s -O -L "$url"
          done < file_urls.txt
      - name: Get aria2c lines
        run: |
          for file in *.ipynb; do
            aria2c_line="$(tail -n 1 "$file" | grep -o '!aria2c.*')"
            echo "$aria2c_line" >> aria2c_lines.txt
          done
      - name: Commit and push changes
        env:
          COMMIT_MSG: "Update aria2c lines"
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add aria2c_lines.txt
          git commit -m "${{ env.COMMIT_MSG }}" -a --author "GitHub Action <action@github.com> (automated commit)"
          git push
