name: Read files

on:
  push:
    branches: [main]

jobs:
  read-files:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Read files
      run: |
        curl -s https://raw.githubusercontent.com/camenduru/stable-diffusion-webui-colab/main/nightly | awk '{print $NF}' > files.txt
    - name: Commit changes
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: "Update files.txt"
        commit_options: "--author 'GitHub Action <action@github.com>'"
