name: Update aria2c lines

on:
  push:
    branches: [main]

jobs:
  update_aria2c_lines:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: List files
        run: |
          curl -s https://api.github.com/repos/camenduru/stable-diffusion-webui-colab/contents/nightly?ref=main \
          | jq -r '.[] | .download_url' > files.txt

      - name: Extract aria2c lines
        run: |
          while read -r file; do
            curl -s "$file" \
            | grep -n -m 1 '!aria2c' \
            | cut -d':' -f2- >> aria2c_lines.txt
          done < files.txt

      - name: Commit and push changes
        env:
          COMMIT_MSG: "Update aria2c lines"
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add aria2c_lines.txt
          git commit -m "${{ env.COMMIT_MSG }}" -a --author "GitHub Action <action@github.com> (automated commit)"
          git push
