name: Extract aria2c lines from files
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Create aria2c lines file
        run: touch aria2c_lines.txt

      - name: Get list of files
        id: list_files
        run: |
          repository_url="https://api.github.com/repos/camenduru/stable-diffusion-webui-colab/contents/nightly"
          files=$(curl -s "$repository_url" | jq -r '.[].name')
          echo "$files" > files.txt

      - name: Extract aria2c lines
        id: extract_lines
        run: |
          while read -r filename; do
            last_line=$(curl -s "https://raw.githubusercontent.com/camenduru/stable-diffusion-webui-colab/main/nightly/$filename" | tac | awk '/aria2c/ {print NR; exit}')
            if [ -n "$last_line" ]; then
              curl -s "https://raw.githubusercontent.com/camenduru/stable-diffusion-webui-colab/main/nightly/$filename" | tail -n +"$last_line" | awk '{print} /^$/ {exit}' >> aria2c_lines.txt
            fi
          done < files.txt
