name: Read files

on:
  push:
    branches: [main]

jobs:
  read-files:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Read files
      run: |
        curl -s https://raw.githubusercontent.com/camenduru/stable-diffusion-webui-colab/main/nightly | awk '{print $NF}' > files.txt
    - name: Commit changes
      run: |
        git config --global user.name 'GitHub Action'
        git config --global user.email 'action@github.com'
        git add files.txt
        git commit -m "Update files.txt"
        git push
