name: Update files.txt and aria2c_lines.txt

on:
  push:
    branches: [main]

jobs:
  update_files:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Get file names
        run: |
          curl -s https://api.github.com/repos/camenduru/stable-diffusion-webui-colab/contents/nightly | grep "name" | cut -d '"' -f 4 > filenames.txt
      - name: Clear aria2c lines file
        run: |
          echo "" > tmp/aria2c_lines.txt
      - name: Get aria2c lines
        run: |
          while read -r filename; do
            curl -s "https://raw.githubusercontent.com/camenduru/stable-diffusion-webui-colab/main/nightly/$filename" | grep -m 1 "!aria2c" >> tmp/aria2c_lines.txt
          done < filenames.txt
      - name: Commit and push changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add filenames.txt tmp/aria2c_lines.txt
          git commit -m "Update files.txt and aria2c_lines.txt" -a --author "GitHub Action <action@github.com> (automated commit)"
          git push
