name: Update files.txt and aria2c_lines.txt

on:
  push:
    branches: [main]

jobs:
  update_files:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Get file names
        run: |
          curl -s https://api.github.com/repos/camenduru/stable-diffusion-webui-colab/contents/nightly | grep "name" | cut -d '"' -f 4 > filenames.txt
      - name: Get aria2c lines
        run: |
          mkdir -p tmp
          while read -r filename; do
            aria2c_page=$(curl -s "https://raw.githubusercontent.com/camenduru/stable-diffusion-webui-colab/main/nightly/$filename")
            last_line=$(echo "$aria2c_page" | grep -n "!aria2c" | tail -1 | cut -d ':' -f 1)
            if [ -n "$last_line" ]; then
              last_line=$((last_line-1))
              echo "$aria2c_page" | head -n $last_line | sed -e 's/[[:space:]]*$//' >> tmp/aria2c_lines.txt
            fi
          done < filenames.txt
      - name: Commit and push changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add filenames.txt tmp/aria2c_lines.txt
          git commit -m "Update files.txt and aria2c_lines.txt" -a --author "GitHub Action <action@github.com> (automated commit)"
          git push
