name: Update files.txt

on:
  push:
    branches: [main]

jobs:
  update_files:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: List files
        run: |
          curl -s https://raw.githubusercontent.com/camenduru/stable-diffusion-webui-colab/main/nightly > files.txt
      - name: Commit and push changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Update files.txt
          commit_options: '--author "GitHub Action <action@github.com>"'
          file_pattern: './*.txt'
