name: Update aria2c_lines.txt

on:
  push:
    branches: [main]

jobs:
  update_files:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: List files
        run: |
          curl -s https://api.github.com/repos/camenduru/stable-diffusion-webui-colab/contents/nightly | jq -r '.[].name' > files.txt
      - name: Search for aria2c commands
        run: |
          while read -r filename; do
            if [[ "$filename" == *".ipynb"* ]]; then
              last_command=$(tail -n 1 "$filename" | grep -oP '!\K[^|]*aria2c[^|]*')
              if [[ -n "$last_command" ]]; then
                echo "$last_command" >> aria2c_lines.txt
              fi
            fi
          done < files.txt
      - name: Commit and push changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add aria2c_lines.txt
          git commit -m "Update aria2c_lines.txt" --author "GitHub Action <action@github.com> (automated commit)"
          git push
