name: Update files.txt

on:
  push:
    branches: [main]

jobs:
  update_files:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: List files
        run: |
          curl -s https://github.com/camenduru/stable-diffusion-webui-colab/tree/main/nightly | grep -oP '(?<=href=")[^"]*(?=")' | grep -E '\.ipynb$' | grep -oP '[^/]+$' > files.txt
      - name: Read files.txt and copy aria2c lines
        run: |
          rm -f aria2c_lines.txt
          while read -r file; do
            url="https://raw.githubusercontent.com/camenduru/stable-diffusion-webui-colab/main/nightly/$file"
            aria2c_line=$(curl -s "$url" | grep -n "!aria2c" | tail -n 1 | cut -d ":" -f 1)
            if [[ -n "$aria2c_line" ]]; then
              ((aria2c_line--))
              while true; do
                last_line=$(curl -s "$url" | sed -n "$aria2c_line{p;q;}")
                if [[ -n "$last_line" ]]; then
                  echo "$last_line" >> aria2c_lines.txt
                  ((aria2c_line--))
                else
                  echo "" >> aria2c_lines.txt
                  break
                fi
              done
            fi
          done < files.txt
      - name: Commit and push changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git commit -m "${{ env.COMMIT_MSG }}" -a --author "GitHub Action <action@github.com> (automated commit)"
          git push
