name: ColabUpdate

on:
  push:
    branches:
      - main
      
jobs:
  remove-keywords:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
 
      - name: Download Colab File
        run: wget -O webui_colab.ipynb https://github.com/camenduru/stable-diffusion-webui-colab/raw/main/nightly/defmix_v2_webui_colab.ipynb

      - name: Remove Keywords
        run: |
          sed -i '/controlnet\|download\.pytorch\.org\|stable-diffusion-webui-rembg\|stable-diffusion-webui-two-shot\|stable-diffusion-webui-huggingface\|deforum-art\|models\/Stable-diffusion -o\|nonnonstop\|sd-webui-additional-networks\|openpose-editor\|depth-lib\|posex/d' webui_colab.ipynb
          sed -i '/!git clone https:\/\/huggingface\.co\/embed\/negative \/content\/stable-diffusion-webui\/embeddings\/negative/d' webui_colab.ipynb
          sed -i '/!git clone https:\/\/huggingface\.co\/embed\/lora \/content\/stable-diffusion-webui\/models\/Lora\/positive/d' webui_colab.ipynb
         
      - name: Replace Colab notebook URL
        run: sed -i 's~https://colab\.research\.google\.com/github/camenduru/stable-diffusion-webui-colab/blob/main/nightly/defmix_v2_webui_colab\.ipynb~https://colab.research.google.com/github/2Cuu/SdWebui/blob/main/webui_colab.ipynb~' webui_colab.ipynb
      
      - name: Output webui_colab.ipynb
        run: |
          sed -i '/"id": "SaAJk33ppFw1"/a\ \ \ \ "cellView": "form"' webui_colab.ipynb
          sed -i '/SaAJk33ppFw1/s/$/,/' webui_colab.ipynb
          sed -i '/TF_CPP_MIN_LOG_LEVEL/ r add/import.txt' webui_colab.ipynb
        shell: bash   

      - name: Append text to webui_colab.ipynb
        run: |
          sed -i '/git reset --hard/ r add/import2.txt' webui_colab.ipynb
          
      - name: Commit Changes
        run: |
          if [[ $(git status --short) ]]; then
            git config --local user.email "action@github.com"
            git config --local user.name "GitHub Action"
            git add webui_colab.ipynb
            git commit -am "Update check"
            git push
          else
            echo "No changes to commit"
          fi
      
      - name: Push Changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          branch: main
          github_token: ${{ secrets.GITHUB_TOKEN }}
