name: Add files to text file

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Get list of files
        id: list_files
        run: |
          repository_url="https://api.github.com/repos/camenduru/stable-diffusion-webui-colab/contents/nightly"
          files=$(curl -s "$repository_url" | jq -r '.[].name')
          printf "%s\n" "${files[@]}" > files.txt
      
      - name: Append to text file
        run: |
          sed -i 's/^/"/;s/$/\\",/' files.txt
          echo "model = \"\" #@param [\"list1\", \"list2\"]" >> files.txt
          cat files.txt
