name: Add files to text file

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Get list of files
        id: list_files
        run: |
          repository_url="https://github.com/camenduru/stable-diffusion-webui-colab.git"
          git ls-remote --tags --heads "$repository_url" "refs/heads/main:nightly/*" | awk '{print $2}' | sed 's:^refs/heads/main:nightly/:g' > files.txt
      
      - name: Append to text file
        run: |
          sed -i 's/^/"/;s/$/\\",/' files.txt
          echo "model = \"\" #@param [\"list1\", \"list2\"]" >> files.txt
          cat files.txt
