name: Update File List

on:
  push:
    branches: [main]
  
jobs:
  remove-keywords:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Delete aria2c_lines.txt
        run: |
          rm tmp/aria2c_lines.txt
      - name: Get file names
        run: |
          curl -s https://api.github.com/repos/camenduru/stable-diffusion-webui-colab/contents/nightly | grep "name" | cut -d '"' -f 4 > filenames.txt
      - name: Get lines containing "models/Stable-diffusion -o"
        run: |
          mkdir -p tmp
          first=true
          while read -r filename; do
              if [ "$first" = true ]; then
                echo "if model == \"$filename\":"
                first=false
              else
                echo "elif model == \"$filename\":"
              fi
                curl -s "https://raw.githubusercontent.com/camenduru/stable-diffusion-webui-colab/main/nightly/$filename" | grep "models/Stable-diffusion -o" | sed 's/^/        /'
          done < filenames.txt >> tmp/aria2c_lines.txt
      
      - name: Pull Changes
        run: git pull
      
      - name: Commit Changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add filenames.txt tmp/aria2c_lines.txt
          git commit -am "Fishxed it"
