name: Output defmix_v2_webui_colab.ipynb workflow

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Output defmix_v2_webui_colab.ipynb
        run: |
          sed -i "/!git reset --hard/a\ \ \ \ \ \ \ \ "model = 'defmix_v2_webui_colab.ipynb' #@param [`cat filenames.txt | sed "s/\(.*\)/'\1',/" | tr -d '\n' | sed 's/,$//'`]"" defmix_v2_webui_colab.ipynb
        shell: bash

      - name: Commit Changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git commit -am "Add model name to defmix_v2_webui_colab.ipynb"
          git push
