name: Update webui

on:
  push:
    branches:
      - main

jobs:
  update_webui:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Append text to defmix_v2_webui_colab.ipynb
        run: |
          sed -i '/model =/ r tmp/aria2c_lines.txt' defmix_v2_webui_colab.ipynb

      - name: Commit changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add defmix_v2_webui_colab.ipynb
          git commit -m "Update webui with aria2c lines"
          git push

      - name: Upload updated notebook
        uses: actions/upload-artifact@v2
        with:
          name: Updated webui
          path: defmix_v2_webui_colab.ipynb
